<a href="https://colab.research.google.com/github/jiyasoni1409-alt/python/blob/main/num3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.
Create a NumPy array representing the number of likes on 7 Instagram posts and print its ndim, shape, size, dtype, itemsize, and nbytes properties.


In [1]:
import numpy as np

# Likes on 7 Instagram posts
likes = np.array([120, 250, 340, 180, 500, 420, 300])

print("Likes:", likes)

print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize, "bytes")
print("nbytes:", likes.nbytes, "bytes")

Likes: [120 250 340 180 500 420 300]
ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8 bytes
nbytes: 56 bytes


2.
Given a 2D NumPy array of daily step counts for 5 days (each row is a day, columns are morning and evening), use reshape() to convert it into a 1D array, then back to a 2D array with 5 rows and 2 columns.<br><br><em><strong>Hint:</strong> Use the shape attribute to check your array after each reshape.</em>


In [2]:
import numpy as np

steps = np.array([
    [3000, 4000],
    [2500, 3500],
    [4000, 4500],
    [2000, 3000],
    [3500, 4200]
])

print("Original 2D array:")
print(steps)

print("Original shape:", steps.shape)

steps_1d = steps.reshape(10)

print("\n1D array:")
print(steps_1d)

print("1D shape:", steps_1d.shape)

steps_2d = steps_1d.reshape(5, 2)

print("\nBack to 2D array:")
print(steps_2d)

print("2D shape:", steps_2d.shape)

Original 2D array:
[[3000 4000]
 [2500 3500]
 [4000 4500]
 [2000 3000]
 [3500 4200]]
Original shape: (5, 2)

1D array:
[3000 4000 2500 3500 4000 4500 2000 3000 3500 4200]
1D shape: (10,)

Back to 2D array:
[[3000 4000]
 [2500 3500]
 [4000 4500]
 [2000 3000]
 [3500 4200]]
2D shape: (5, 2)


3.
Build a NumPy array representing the prices of 12 food items from a Zomato order, then use ravel(), flatten(), and resize() to create different shaped versions of the data and print each result.<br><br><em><strong>Constraint:</strong> Show the difference between ravel() and flatten() in your code comments.</em>


In [3]:
import numpy as np

# Prices of 12 Zomato food items
prices = np.array([
    120, 250, 180, 90,
    300, 150, 220, 100,
    275, 130, 200, 350
])

print("Original prices:")
print(prices)

# Reshape into 3 rows and 4 columns
prices_2d = prices.reshape(3, 4)

print("\n2D prices:")
print(prices_2d)

ravel_prices = prices_2d.ravel()

print("\nUsing ravel():")
print(ravel_prices)

flatten_prices = prices_2d.flatten()

print("\nUsing flatten():")
print(flatten_prices)

# resize() changes the size/shape of the array
resized_prices = prices_2d.copy()
resized_prices.resize(4, 3)

print("\nUsing resize():")
print(resized_prices)

Original prices:
[120 250 180  90 300 150 220 100 275 130 200 350]

2D prices:
[[120 250 180  90]
 [300 150 220 100]
 [275 130 200 350]]

Using ravel():
[120 250 180  90 300 150 220 100 275 130 200 350]

Using flatten():
[120 250 180  90 300 150 220 100 275 130 200 350]

Using resize():
[[120 250 180]
 [ 90 300 150]
 [220 100 275]
 [130 200 350]]


4.
Take a 3x3 NumPy array representing a mini Spotify playlist grid (rows: playlists, columns: song counts in categories like Pop, Rock, Indie). Use both T and np.transpose() to swap rows and columns, then print the transposed array.


In [4]:
import numpy as np

playlist = np.array([
    [10, 5, 8],
    [7, 12, 6],
    [15, 4, 10]
])

print("Original playlist grid:")
print(playlist)

# Transpose using T
transposed_T = playlist.T

print("\nTranspose using T:")
print(transposed_T)

transposed_function = np.transpose(playlist)

print("\nTranspose using np.transpose():")
print(transposed_function)

Original playlist grid:
[[10  5  8]
 [ 7 12  6]
 [15  4 10]]

Transpose using T:
[[10  7 15]
 [ 5 12  4]
 [ 8  6 10]]

Transpose using np.transpose():
[[10  7 15]
 [ 5 12  4]
 [ 8  6 10]]


5.
Given a 1D NumPy array of 15 Flipkart product ratings, use reshape() to convert it into a 3x5 array, then use flatten() to return it to a 1D array. Explain in a comment when you would use flatten() versus ravel() in real projects.

In [5]:
import numpy as np

ratings = np.array([
    4, 5, 3, 4, 2,
    5, 4, 3, 5, 4,
    2, 3, 5, 4, 5
])

print("Original 1D ratings:")
print(ratings)

print("Original shape:", ratings.shape)

# Convert 1D array into 3x5 array
ratings_2d = ratings.reshape(3, 5)

print("\n3x5 ratings array:")
print(ratings_2d)

print("New shape:", ratings_2d.shape)

# Convert 2D array back to 1D
ratings_1d = ratings_2d.flatten()

print("\nAfter flatten():")
print(ratings_1d)

print("Final shape:", ratings_1d.shape)


Original 1D ratings:
[4 5 3 4 2 5 4 3 5 4 2 3 5 4 5]
Original shape: (15,)

3x5 ratings array:
[[4 5 3 4 2]
 [5 4 3 5 4]
 [2 3 5 4 5]]
New shape: (3, 5)

After flatten():
[4 5 3 4 2 5 4 3 5 4 2 3 5 4 5]
Final shape: (15,)
