<a href="https://colab.research.google.com/github/jiyasoni1409-alt/python/blob/main/num7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.
Create two NumPy arrays representing the ratings of 5 restaurants on Zomato and Swiggy, then use np.concatenate() to combine them into a single array of 10 ratings and print the result.


In [1]:
import numpy as np

zomato = np.array([4.5, 4.2, 3.8, 4.7, 4.0])

swiggy = np.array([4.1, 3.9, 4.6, 4.3, 4.8])

combined = np.concatenate((zomato, swiggy))

print("Zomato ratings:")
print(zomato)

print("\nSwiggy ratings:")
print(swiggy)

print("\nCombined ratings:")
print(combined)

Zomato ratings:
[4.5 4.2 3.8 4.7 4. ]

Swiggy ratings:
[4.1 3.9 4.6 4.3 4.8]

Combined ratings:
[4.5 4.2 3.8 4.7 4.  4.1 3.9 4.6 4.3 4.8]


2.
Given three arrays representing the number of likes on three different Instagram posts over 7 days, stack them vertically using np.vstack() so that each row represents one post's weekly likes, and print the stacked array.


In [2]:
import numpy as np

post1 = np.array([100, 120, 150, 180, 200, 220, 250])

post2 = np.array([80, 110, 140, 160, 190, 210, 230])

post3 = np.array([90, 130, 160, 170, 210, 240, 280])

weekly_likes = np.vstack((post1, post2, post3))

print("Weekly Instagram likes:")
print(weekly_likes)

print("\nShape:")
print(weekly_likes.shape)

Weekly Instagram likes:
[[100 120 150 180 200 220 250]
 [ 80 110 140 160 190 210 230]
 [ 90 130 160 170 210 240 280]]

Shape:
(3, 7)


3.
You have an array of 12 Flipkart product IDs. Use np.array_split() to divide this array into 5 nearly equal parts, and display each part.<br><br><em><strong>Hint:</strong> Check the shape of each split to confirm the division.</em>


In [3]:
import numpy as np

product_ids = np.array([
    101, 102, 103, 104,
    105, 106, 107, 108,
    109, 110, 111, 112
])

parts = np.array_split(product_ids, 5)

print("Original Product IDs:")
print(product_ids)

print("\n5 Parts:")

for i, part in enumerate(parts, start=1):
    print("Part", i, ":", part)
    print("Shape:", part.shape)

Original Product IDs:
[101 102 103 104 105 106 107 108 109 110 111 112]

5 Parts:
Part 1 : [101 102 103]
Shape: (3,)
Part 2 : [104 105 106]
Shape: (3,)
Part 3 : [107 108]
Shape: (2,)
Part 4 : [109 110]
Shape: (2,)
Part 5 : [111 112]
Shape: (2,)


4.
Simulate a WhatsApp group chat: create a 2D NumPy array where each row is a user and each column is the number of messages sent per day for a week. Use np.insert() to add a new user (row) with their message counts, then use np.delete() to remove the user who sent the least messages overall.


In [4]:
import numpy as np

messages = np.array([
    [20, 25, 30, 15, 40, 35, 25],
    [10, 15, 20, 12, 18, 15, 10],
    [30, 35, 25, 40, 45, 30, 35]
])

print("Original WhatsApp group data:")
print(messages)

new_user = np.array([15, 20, 18, 25, 22, 20, 17])

messages = np.insert(messages, 1, new_user, axis=0)

print("\nAfter adding new user:")
print(messages)

total_messages = messages.sum(axis=1)

print("\nTotal messages by each user:")
print(total_messages)

least_user = np.argmin(total_messages)

print("\nUser with least messages is at row:", least_user)

messages = np.delete(messages, least_user, axis=0)

print("\nAfter removing the user with least messages:")
print(messages)

Original WhatsApp group data:
[[20 25 30 15 40 35 25]
 [10 15 20 12 18 15 10]
 [30 35 25 40 45 30 35]]

After adding new user:
[[20 25 30 15 40 35 25]
 [15 20 18 25 22 20 17]
 [10 15 20 12 18 15 10]
 [30 35 25 40 45 30 35]]

Total messages by each user:
[190 137 100 240]

User with least messages is at row: 2

After removing the user with least messages:
[[20 25 30 15 40 35 25]
 [15 20 18 25 22 20 17]
 [30 35 25 40 45 30 35]]


5.
Given a NumPy array of YouTube video view counts, use .view() to create a view and .copy() to create a copy. Modify the first element in each and print all arrays to demonstrate the difference between view and copy.<br><br><em><strong>Hint:</strong> Observe which changes affect the original array.</em>

In [5]:
import numpy as np

views = np.array([1000, 2500, 5000, 7500, 10000])

views_view = views.view()

views_copy = views.copy()

views_view[0] = 9999

views_copy[0] = 8888

print("Original array:")
print(views)

print("\nView:")
print(views_view)

print("\nCopy:")
print(views_copy)

Original array:
[ 9999  2500  5000  7500 10000]

View:
[ 9999  2500  5000  7500 10000]

Copy:
[ 8888  2500  5000  7500 10000]
