<a href="https://colab.research.google.com/github/jiyasoni1409-alt/python/blob/main/num8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.
Given a NumPy array of IPL team names with some duplicates, use np.unique() to print a sorted list of all unique team names.


In [5]:
import numpy as np

teams = np.array([
    "MI", "CSK", "RCB", "MI", "KKR",
    "CSK", "GT", "RCB", "MI", "GT"
])

unique_teams = np.unique(teams)

print("Original teams:")
print(teams)

print("\nUnique IPL teams:")
print(unique_teams)

Original teams:
['MI' 'CSK' 'RCB' 'MI' 'KKR' 'CSK' 'GT' 'RCB' 'MI' 'GT']

Unique IPL teams:
['CSK' 'GT' 'KKR' 'MI' 'RCB']


2.
Create a NumPy array of Zomato order ratings (with some NaN values), then use np.isnan() to count how many ratings are missing.


In [4]:
import numpy as np

ratings = np.array([4.5, np.nan, 3.8, 4.2, np.nan, 5.0, 3.5])

missing_values = np.isnan(ratings)

missing_count = np.sum(missing_values)

print("Zomato ratings:")
print(ratings)

print("\nMissing value positions:")
print(missing_values)

print("\nNumber of missing ratings:", missing_count)

Zomato ratings:
[4.5 nan 3.8 4.2 nan 5.  3.5]

Missing value positions:
[False  True False False  True False False]

Number of missing ratings: 2


3.
Given an array of Flipkart product prices, use np.clip() to limit all prices between 100 and 1000, and print the resulting array.<br><br><em><strong>Hint:</strong> Use np.clip(array, 100, 1000).</em>


In [3]:
import numpy as np

prices = np.array([50, 150, 450, 750, 1200, 2000, 80, 999])

clipped_prices = np.clip(prices, 100, 1000)

print("Original prices:")
print(prices)

print("\nPrices after clipping:")
print(clipped_prices)

Original prices:
[  50  150  450  750 1200 2000   80  999]

Prices after clipping:
[ 100  150  450  750 1000 1000  100  999]


4.
You have a NumPy array of YouTube video view counts, some of which are NaN or inf. Replace all NaN values with 0, and all inf values with the maximum finite value in the array.


In [2]:
import numpy as np

views = np.array([
    1000, 2500, np.nan, 5000,
    np.inf, 7500, np.nan, 10000
])

print("Original views:")
print(views)

max_finite = np.max(views[np.isfinite(views)])

clean_views = np.nan_to_num(
    views,
    nan=0,
    posinf=max_finite,
    neginf=max_finite
)

print("\nMaximum finite value:", max_finite)

print("\nCleaned views:")
print(clean_views)

Original views:
[ 1000.  2500.    nan  5000.    inf  7500.    nan 10000.]

Maximum finite value: 10000.0

Cleaned views:
[ 1000.  2500.     0.  5000. 10000.  7500.     0. 10000.]


5.
Use ChatGPT to generate a Python code snippet that finds the indices of all even numbers in a NumPy array using np.where(), then test the code with your own example array.

In [1]:
import numpy as np

numbers = np.array([11, 24, 35, 42, 57, 68, 73, 80, 91, 100])

even_indices = np.where(numbers % 2 == 0)

print("Original array:")
print(numbers)

print("\nIndices of even numbers:")
print(even_indices[0])

Original array:
[ 11  24  35  42  57  68  73  80  91 100]

Indices of even numbers:
[1 3 5 7 9]
