1.
Install NumPy using pip and write a Python script list_vs_array.py that creates a list and a NumPy array, each containing the numbers from 1 to 1000.


In [5]:
import numpy as np

# Python list containing numbers 1 to 1000
my_list = list(range(1, 1001))

# NumPy array containing numbers 1 to 1000
my_array = np.arange(1, 1001)

print("Python List:")
print(my_list)

print("\nNumPy Array:")
print(my_array)

Python List:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,

2.
In your script, measure and print the memory usage (in bytes) of both the Python list and the NumPy array containing 1000 integers.<br><br><em><strong>Hint:</strong> Use the sys.getsizeof() function for the list and the nbytes attribute for the NumPy array.</em>


In [6]:
import numpy as np
import sys

# Create Python list
my_list = list(range(1, 1001))

# Create NumPy array
my_array = np.arange(1, 1001)

# Calculate memory usage
list_memory = sys.getsizeof(my_list)
array_memory = my_array.nbytes

# Print memory usage
print("Memory usage of Python List:", list_memory, "bytes")
print("Memory usage of NumPy Array:", array_memory, "bytes")

Memory usage of Python List: 8056 bytes
Memory usage of NumPy Array: 8000 bytes


3.
Write a function compare_addition_speed() that adds 5 to every element in both a Python list and a NumPy array of 10,000 integers, and prints the time taken for each.<br><br><em><strong>Hint:</strong> Use the time module to measure execution time.</em>


In [7]:
import numpy as np
import time

def compare_addition_speed():

    # Create Python list
    my_list = list(range(1, 10001))

    # Create NumPy array
    my_array = np.arange(1, 10001)

    # Python list addition using for-loop
    start_time = time.time()

    list_result = []
    for number in my_list:
        list_result.append(number + 5)

    list_time = time.time() - start_time

    start_time = time.time()

    array_result = my_array + 5

    array_time = time.time() - start_time

    print("Time taken by Python List:", list_time, "seconds")
    print("Time taken by NumPy Array:", array_time, "seconds")


compare_addition_speed()

Time taken by Python List: 0.0006344318389892578 seconds
Time taken by NumPy Array: 0.00011777877807617188 seconds


4.
Explain with code how vectorized operations in NumPy can replace for-loops when multiplying all elements of an array by 2. Show both the loop and the vectorized version using a Zomato-style example: multiplying all restaurant ratings by 2.

In [8]:
import numpy as np


ratings = np.array([2.5, 3.0, 3.5, 4.0, 4.5])

# Vectorized operation
new_ratings = ratings * 2

print("Original Ratings:")
print(ratings)

print("\nRatings after multiplying by 2:")
print(new_ratings)

Original Ratings:
[2.5 3.  3.5 4.  4.5]

Ratings after multiplying by 2:
[5. 6. 7. 8. 9.]


using for loop


In [9]:
import numpy as np

# Zomato-style restaurant ratings
ratings = np.array([2.5, 3.0, 3.5, 4.0, 4.5])

# Empty list to store results
new_ratings = []

# Multiply each rating by 2 using a loop
for rating in ratings:
    new_ratings.append(rating * 2)

print("Original Ratings:")
print(ratings)

print("\nRatings after multiplying by 2:")
print(new_ratings)

Original Ratings:
[2.5 3.  3.5 4.  4.5]

Ratings after multiplying by 2:
[np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]
