1.
Create a NumPy array called my_scores using np.array() with your last 5 Zomato order ratings (pick any integers between 1 and 5), and print the array.


In [1]:
import numpy as np

# Last 5 Zomato order ratings
my_scores = np.array([4, 5, 3, 4, 5])

print("My Zomato ratings:")
print(my_scores)

My Zomato ratings:
[4 5 3 4 5]


2.
Use np.arange() to generate an array of all even numbers between 10 and 30 (inclusive), then print the result.


In [2]:
import numpy as np

# Generate even numbers from 10 to 30
even_numbers = np.arange(10, 31, 2)

print("Even numbers:")
print(even_numbers)

Even numbers:
[10 12 14 16 18 20 22 24 26 28 30]


3.
Generate an array of 8 equally spaced values between 0 and 1 using np.linspace(), and print the array.<br><br><em><strong>Hint:</strong> This is similar to how Spotify creates smooth volume sliders.</em>


In [3]:
import numpy as np

# Generate 8 equally spaced values between 0 and 1
volume = np.linspace(0, 1, 8)

print("Spotify-style volume values:")
print(volume)

Spotify-style volume values:
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


4.
Simulate a Flipkart-style 'Add to Cart' button counter by creating a NumPy array of 10 zeros using np.zeros(), then update the 3rd and 7th items to 1 (representing items added to cart), and print the updated array.


In [4]:
import numpy as np

# Create an array of 10 zeros
cart = np.zeros(10, dtype=int)

# Update 3rd and 7th items to 1
cart[2] = 1
cart[6] = 1

print("Updated cart:")
print(cart)

Updated cart:
[0 0 1 0 0 0 1 0 0 0]


5.
Use np.random.randint() to create an array of 6 random integers between 1000 and 9999 (representing random OTP codes like Paytm), and print the array.<br><br><em><strong>Constraint:</strong> Set the random seed to 42 using np.random.seed(42) before generating the array so your results are reproducible.</em>

In [5]:
import numpy as np

np.random.seed(42)

otp_codes = np.random.randint(1000, 10000, 6)

print("Random OTP codes:")
print(otp_codes)

Random OTP codes:
[8270 1860 6390 6191 6734 7265]
