1.
Create two NumPy arrays representing the number of likes on your last 7 Instagram posts and your friend's last 7 posts, then use np.add() and np.subtract() to calculate both the combined and difference arrays.


In [1]:
import numpy as np

my_likes = np.array([120, 250, 340, 180, 500, 420, 300])

friend_likes = np.array([100, 300, 280, 200, 450, 400, 350])

combined = np.add(my_likes, friend_likes)

difference = np.subtract(my_likes, friend_likes)

print("My likes:", my_likes)
print("Friend's likes:", friend_likes)
print("Combined likes:", combined)
print("Difference:", difference)

My likes: [120 250 340 180 500 420 300]
Friend's likes: [100 300 280 200 450 400 350]
Combined likes: [220 550 620 380 950 820 650]
Difference: [ 20 -50  60 -20  50  20 -50]


2.
Given a NumPy array of item prices from your last Zomato order, use np.multiply() to apply a 10% discount on each item, then use np.sum() to calculate the final bill amount after discount.<br><br><em><strong>Hint:</strong> To apply a 10% discount, multiply each price by 0.9.</em>


In [2]:
import numpy as np

prices = np.array([250, 180, 300, 150, 220])

discounted_prices = np.multiply(prices, 0.9)

final_bill = np.sum(discounted_prices)

print("Original prices:", prices)
print("Prices after 10% discount:", discounted_prices)
print("Final bill amount:", final_bill)

Original prices: [250 180 300 150 220]
Prices after 10% discount: [225. 162. 270. 135. 198.]
Final bill amount: 990.0


3.
Take a NumPy array of daily step counts for the last 30 days (you can make up the numbers), and use np.mean(), np.median(), np.std(), and np.max() to analyze your fitness stats like a health app would.


In [3]:
import numpy as np

steps = np.array([
    5000, 6500, 7000, 4500, 8000,
    6000, 7500, 5500, 6800, 7200,
    4900, 6200, 7100, 8300, 5900,
    6400, 7700, 6900, 5800, 8100,
    5300, 6700, 7400, 6000, 8500,
    5600, 7000, 7800, 6300, 8200
])

mean_steps = np.mean(steps)
median_steps = np.median(steps)
std_steps = np.std(steps)
max_steps = np.max(steps)

print("Daily steps:", steps)
print("Mean steps:", mean_steps)
print("Median steps:", median_steps)
print("Standard deviation:", std_steps)
print("Maximum steps:", max_steps)

Daily steps: [5000 6500 7000 4500 8000 6000 7500 5500 6800 7200 4900 6200 7100 8300
 5900 6400 7700 6900 5800 8100 5300 6700 7400 6000 8500 5600 7000 7800
 6300 8200]
Mean steps: 6670.0
Median steps: 6750.0
Standard deviation: 1067.7546534667972
Maximum steps: 8500


4.
Create a NumPy array of 10 random float ratings (between 1 and 5) for a new movie on BookMyShow, then use np.round(), np.floor(), and np.ceil() to show how the rating would appear if rounded to the nearest whole number, always rounded down, and always rounded up.


In [4]:
import numpy as np

np.random.seed(42)

ratings = np.random.uniform(1, 5, 10)

print("Original movie ratings:")
print(ratings)

rounded = np.round(ratings)

rounded_down = np.floor(ratings)

rounded_up = np.ceil(ratings)

print("\nRounded ratings:")
print(rounded)

print("\nRatings rounded down:")
print(rounded_down)

print("\nRatings rounded up:")
print(rounded_up)

Original movie ratings:
[2.49816048 4.80285723 3.92797577 3.39463394 1.62407456 1.62397808
 1.23233445 4.46470458 3.40446005 3.83229031]

Rounded ratings:
[2. 5. 4. 3. 2. 2. 1. 4. 3. 4.]

Ratings rounded down:
[2. 4. 3. 3. 1. 1. 1. 4. 3. 3.]

Ratings rounded up:
[3. 5. 4. 4. 2. 2. 2. 5. 4. 4.]


5.
Use ChatGPT to generate Python code that calculates the percentage of songs you skipped in your last 20 Spotify plays using NumPy arrays and np.percentile(), then run the code and paste your output.<br><br><em><strong>Hint:</strong> Ask ChatGPT for code that finds the 75th percentile of skips in a NumPy array.</em>

In [5]:
import numpy as np

skips = np.array([
    0, 1, 0, 0, 1,
    0, 1, 0, 1, 0,
    0, 1, 0, 0, 1,
    0, 1, 0, 1, 0
])

skip_percentage = np.mean(skips) * 100

percentile_75 = np.percentile(skips, 75)

print("Spotify skip data:")
print(skips)

print("Percentage of songs skipped:", skip_percentage, "%")
print("75th percentile of skips:", percentile_75)

Spotify skip data:
[0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0]
Percentage of songs skipped: 40.0 %
75th percentile of skips: 1.0
