1.
Create a NumPy array called prices with the following values: [199, 299, 399, 499, 599]. Use basic indexing to print the first and last price.


In [1]:
import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First price:", prices[0])

print("Last price:", prices[-1])

First price: 199
Last price: 599


2.
Given a 2D NumPy array representing cricket scores for 3 players across 5 matches, use slicing to extract the scores of all players for matches 2 to 4 (index 1 to 3).


In [2]:
import numpy as np

scores = np.array([
    [45, 60, 72, 55, 80],
    [50, 65, 68, 75, 90],
    [30, 55, 61, 70, 85]
])

print("Original scores:")
print(scores)

selected_scores = scores[:, 1:4]

print("\nScores for matches 2 to 4:")
print(selected_scores)

Original scores:
[[45 60 72 55 80]
 [50 65 68 75 90]
 [30 55 61 70 85]]

Scores for matches 2 to 4:
[[60 72 55]
 [65 68 75]
 [55 61 70]]


3.
You have a NumPy array called ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5]). Use negative indexing to print the last three ratings.


In [3]:
import numpy as np

ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

last_three = ratings[-3:]

print("Last three ratings:")
print(last_three)

Last three ratings:
[2.9 5.  3.5]


4.
Create a NumPy array of the first 20 natural numbers. Use step slicing to print every 3rd number starting from the second element.<br><br><em><strong>Hint:</strong> Use the slice notation with a step value.</em>


In [4]:
import numpy as np

numbers = np.arange(1, 21)

print("Natural numbers:")
print(numbers)

result = numbers[1::3]

print("\nEvery 3rd number starting from second element:")
print(result)

Natural numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Every 3rd number starting from second element:
[ 2  5  8 11 14 17 20]


5.
Given a NumPy array of Flipkart product prices, use boolean indexing to extract all prices greater than 500. Print the resulting array.


In [5]:
import numpy as np

prices = np.array([250, 650, 450, 799, 320, 1200, 550, 480])

high_prices = prices[prices > 500]

print("All prices:")
print(prices)

print("\nPrices greater than 500:")
print(high_prices)

All prices:
[ 250  650  450  799  320 1200  550  480]

Prices greater than 500:
[ 650  799 1200  550]


6.
You have an array of IPL team scores: np.array([210, 180, 195, 220, 205, 175]). Use np.where() to find the indices of all scores above 200 and print these indices.

In [6]:
import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])

indices = np.where(scores > 200)

print("IPL scores:")
print(scores)

print("\nIndices of scores above 200:")
print(indices[0])

IPL scores:
[210 180 195 220 205 175]

Indices of scores above 200:
[0 3 4]
